const QUIZ_DATA = [
{ no: 1,  ja: "気候変動が非常に深刻であることは確かだ。",    en: "It is certain that climate change is very serious.", kaisetsu: "thatが導く名詞節（〈that S′ V′〉「～ということ」、ここでは「気候変動が非常に深刻であるということ」〈That climate change is very serious〉）が主語として文頭に置かれると，主部の長いバランスの悪い文になることが多い〈That climate change is very serious is certain.〉。これを避けるため，文頭にitを置きthat節を後ろに移動させるのがふつう。このitを「形式主語」といい，本来の主語であるthat節を「真主語」という（形式主語it自体には意味がないので，「それは」と訳さない）。このような型の文を「形式主語構文」という。" },
{ no: 2,  ja: "人の行動を変えるのは難しい。",    en: "It is difficult to change oneʼs behavior." , kaisetsu: "to不定詞句（to不定詞形の動詞から始まるまとまり。ここでは「人の行動を変えること」〈to change one's behavior〉）が主語である文においても，特に句が長い場合に，It is ... to do「～することは…だ」の形式主語構文となる。（to change の to～は「～すること」という名詞的用法。)"},
{ no: 3,  ja: "彼女がその手紙を書くのに３時間かかった。",    en: "It took her three hours to write the letter." },
{ no: 4,  ja: "彼がカナダでスキーをするのに2,500ドルかかった。",    en: "It cost him 2,500 dollars to ski in Canada." },
{ no: 5,  ja: "この証拠から，彼女は無実だということになる。",    en: "From this evidence, it follows that she is innocent." },
{ no: 6,  ja: "ここから横浜駅までは５キロの距離だ。",    en: "It is five kilometers from here to Yokohama Station.", kaisetsu: "〈It is＋距離（＋from A）to B〉は，（A地点から）B地点までの距離を表す表現。このitは明確な意味を持たないが，英語の文では主語が必要になるため，文の形を整えるために置かれている（「非人称のit」という）。itにはこのように，〈距離〉あるいは〈時間〉，〈天気〉，〈寒暖〉，〈明暗〉などを表す用法がある。このitは「それ」とは訳さない。 " },
{ no: 7,  ja: "あなたに最後にお会いして以来，３か月が経つ。",    en: "It has been three months since I last saw you.", kaisetsu: "〈It has been[is] ... since S′＋過去形〉は，ある過去の時点やある過去の出来事が起こった時点から今まで，どれくらい時間が経ったかを述べる表現。このitも漠然と時間を表すものであり，「それは」と訳さない。述語動詞はhas beenまたはisとなる。  " },
{ no: 8,  ja: "彼が自分の家を買えるまで数年かかるだろう。",    en: "It will be several years before he can buy his own house.", kaisetsu: "〈It＋be動詞 ～ before[until] ...〉は，No.7とは対照的に、未来のある時点までどれくらいの時間がかかるかを述べる表現。No.7はsinceを用いたが,ここではbefore [またはuntil]を用いることに注意。まだ起こっていない未来のことなので、基本例文のように推量の助動詞を伴ってIt will[would] be ～ という形になることが多い。また、beforeの後にS'+ V'が来る場合、その動詞の時制は現在形になることも一つのポイント（時や条件を表す副詞節では未来のことも現在形で代用する、というルール）。No.7とNo.8はセットで覚えるとよい。なお、No.8は過去のある時点までかかったという内容も表すことができ、その場合は It was～ となる。 " },
{ no: 9,  ja: "ルーカスはエマのことが大好きなようだ。",    en: "Lucas seems to love Emma.", kaisetsu: "seem[appear] toは，have to ～（～しなければならない）, be able to ～ (～することができる）と同じように，〈動詞＋to〉を１つのまとまりとしてとらえる。また、〈S seem[appear] to do.〉は，〈It seems[appears] that S′V′.〉という表現で書き換えられる。 It seems that Lucas loves Emma. " },
{ no: 10,  ja: "息子はじきに読み書きができるようになるだろう。",    en: "My son will learn to read and write soon.", kaisetsu: "learn toも，seem toと同じように〈動詞＋to〉を１つのまとまりとしてとらえるべき表現。learnの中心の意味は「学ぶ」なので，〈learn to do〉は「自ら学んで～する［できる］ようになる」というニュアンス。主に何かの技能が身につくという場合に使う。過去形は〈learned to do〉となる。  " },
{ no: 11,  ja: "彼は大声で話す傾向がある。",    en: "He tends to speak in a loud voice." },
{ no: 12,  ja: "私はどうにか締め切りまでにレポートを仕上げることができた。",    en: "I managed to finish my report by the deadline." },
{ no: 13,  ja: "昔はよく家の近くの川で泳いだものだ。",    en: "I used to swim in the river near my house." },
{ no: 14,  ja: "今まさに電車が出るところだ。",    en: "The train is about to leave." },
{ no: 15,  ja: "その男は莫大な富を持っていると言われている。",    en: "The man is said to possess great wealth." },
{ no: 16,  ja: "リサはたぶん，じきに仕事を辞めるだろう。",    en: "Lisa may well leave her job soon." },
{ no: 17,  ja: "その赤ちゃんは一晩中泣き続けた。",    en: "The baby kept crying all night." },
{ no: 18,  ja: "彼は遅いな。電車に乗り遅れたのかもしれない。",    en: "Heʼs late. He may have missed the train." },
{ no: 19,  ja: "彼らはあまりにも疲れていて動けなかった。",    en: "They were too tired to move." },
{ no: 20,  ja: "彼女のスカートは床に触れるほど長かった。",    en: "Her skirt was long enough to touch the floor." },
{ no: 21,  ja: "より良い社会を創るために私たちは懸命に働いている。",    en: "We are working hard in order to create a better society." },
{ no: 22,  ja: "私たちは家を買う余裕がない。",    en: "We cannot afford to buy a house." },
{ no: 23,  ja: "彼女は私に窓を開けるよう頼んだ。",    en: "She asked me to open the window." },
{ no: 24,  ja: "コーチは時々日曜日にも私たちに練習させる。",    en: "Our coach sometimes makes us practice even on Sundays." },
{ no: 25,  ja: "ブラウン医師は看護師に私の血圧を測らせた。",    en: "Dr.Brown had the nurse take my blood pressure." },
{ no: 26,  ja: "私は息子に自分のギターを弾かせてやった。",    en: "I let my son play my guitar." },
{ no: 27,  ja: "私たちは深い雪の中，その男性が車を押すのを手助けした。",    en: "We helped the man push his car in the deep snow." },
{ no: 28,  ja: "彼の妻は彼がその店に入るのを見た。",    en: "His wife saw him go into the shop." },
{ no: 29,  ja: "私はもう一度挑戦したが，結局失敗しただけだった。",    en: "I tried it again, only to fail." },
{ no: 30,  ja: "彼女は外出して，二度と戻ってこなかった。",    en: "She went out, never to return." },
{ no: 31,  ja: "大統領は間もなくここに着くことになっている。",    en: "The president is to arrive here soon." },
{ no: 32,  ja: "私たちは次に何をするべきかについて話した。",    en: "We talked about what to do next." },
{ no: 33,  ja: "私には車を売るほかなかった。",    en: "I had no choice but to sell my car." },
{ no: 34,  ja: "あなたはその組織と何らかの関係がありますか？",    en: "Do you have something to do with the organization?" },
{ no: 35,  ja: "彼は本と新聞を読むことで自分の英語に磨きをかけた。",    en: "He improved his English by reading books and newspapers." },
{ no: 36,  ja: "彼は何も言わないで部屋を出ていった。",    en: "He left the room without saying anything." },
{ no: 37,  ja: "教育を改革する際には，学生の意見を考慮に入れるべきだ。",    en: "In reforming education, studentsʼ opinions should be considered." },
{ no: 38,  ja: "その音を聞くや否や，そのイヌは逃げていった。",    en: "On hearing the sound, the dog ran away." },
{ no: 39,  ja: "その子どもたちは学校に行くかわりに働いている。",    en: "The children are working instead of going to school." },
{ no: 40,  ja: "私たちはあなたにお会いするのを楽しみにしています。",    en: "We are looking forward to seeing you." },
{ no: 41,  ja: "この都市は訪れる価値がある。",    en: "This city is worth visiting." },
{ no: 42,  ja: "私は大学に行ったら新しいクラブに入ることに興味をもっている。",    en: "I am interested in joining new clubs when I go to university." },
{ no: 43,  ja: "（強風が，多くの電車が時間通りに運行することを妨げた。→）\n強風のために，多くの電車が時間通りに運行できなかった。",    en: "The windy weather prevented many trains from running on time." },
{ no: 44,  ja: "私は毎晩ゲームをせずにはいられない。",    en: "I cannot help playing games every night." },
{ no: 45,  ja: "彼が次に何をするか，知ることはできない。",    en: "There is no knowing what he will do next." },
{ no: 46,  ja: "私を脅しても無駄ですよ。",    en: "Itʼs no use threatening me." },
{ no: 47,  ja: "私たちはネコが小さなネズミを追いかけているのを見た。",    en: "We saw a cat chasing a little mouse." },
{ no: 48,  ja: "私は自分の名前が後ろから呼ばれるのを聞いた。",    en: "I heard my name called from behind." },
{ no: 49,  ja: "私たちは一晩中ストーブをたいておいた。",    en: "We kept the stove burning throughout the night." },
{ no: 50,  ja: "鼻と口がマスクで覆われたままにしておいてください。",    en: "Please keep your nose and mouth covered with a mask." },
{ no: 51,  ja: "私は専門家に自分のパソコンをチェックしてもらった。",    en: "I had my PC checked by a specialist." },
{ no: 52,  ja: "私は英語で理解してもらえなかった。",    en: "I couldnʼt make myself understood in English." },
{ no: 53,  ja: "気分が良くなかったので，私は早くベッドに入った。",    en: "Not feeling well, I went to bed early." },
{ no: 54,  ja: "簡単な英語で書かれているので，この本は初心者に向いている。",    en: "Written in easy English, this book is suitable for beginners." },
{ no: 55,  ja: "雨が降りはじめたので，彼らはタクシーに乗ることにした。",    en: "The rain beginning to fall, they decided to take a taxi." },
{ no: 56,  ja: "厳密に言えば，彼の意見は僕の意見とは少し異なる。",    en: "Strictly speaking, his opinion is a little different from mine.", kaisetsu: "〈strictly speaking, ...〉は「厳密に言えば，…」の意味で，分詞構文の慣用表現の1つである。different は「異なる」という意味だが、fromと相性がよく, different from ～で「～と異なる」と使う。a littleは違いがどれだけあるのかという異なる度合いを示している。分詞構文を用いた慣用表現としては，次のようなものがある。覚えるしかないので頑張ろう。► all things considered「すべてのことを考慮すると」► (all) other things being equal「他の（すべての）条件が同じであれば」► such being the case「そういうわけで」※「such（そのようなこと）が the case（真実）であるので」が直訳。► weather permitting「天気が許せば」► frankly speaking「率直に言うと」► generally speaking「一般的に言うと」► speaking[talking] of ...「…について言うと／…と言えば」► judging from ...「…から判断すると」► considering (that) ...「…を考慮すると［しても］」► assuming (that) ...「…だと仮定して／…だとすると」► seeing (that) ...「…を考えると／…なので[だから]」► taking ... into consideration「…を考慮に入れると［入れて］」など。" },
{ no: 57,  ja: "そのテーマを調査するのに私たちは２週間を費やした。",    en: "We spent two weeks researching the topic.", kaisetsu: "<spend + 時間 + ～ing＞で「～して時間を過ごす」となる。「～することで時間を過ごす」であっても<spend + 時間 + ～ing＞のままであり、時間についてのspendは「この形で使う」と覚えよう。なお、spendには「お金を使う」という意味もあり、こちらは<spend + お金 + on 品物＞という形で使う。これも重要。本構文で用いられるdoingを「～しながら」という意味の分詞構文だと考えることも可能だが，むしろ〈spend＋時間＋doing〉のひとかたまりで「～するのに…の時間を費やす」の意味ととらえ，1つの慣用表現として記憶するほうがよい。► You should spend a lot of time reading.「君は多くの時間を読書に費やすべきだ」 " },
{ no: 58,  ja: "エンジンをかけたまま，車を離れないでください。",    en: "Donʼt leave your car with the engine running.", kaisetsu: "〈with A doing〉は「Aが～している状態で」の意味。Aは～ingの動詞の意味上の主語に当たる。withは「一緒に」という意味なので，このwithが存在することにより，doingと主節のVが時間的に「一緒」（＝同時）だということが示される。このwithは「付帯状況のwith」と呼ばれる。 " },
{ no: 59,  ja: "彼は（腕が組まれた状態で→）腕を組んで立っていた。",    en: "He was standing with his arms crossed.", kaisetsu: "〈with A done〉は「Aが～された状態で」の意味。これもNo.58と同じ「付帯状況のwith」。No.58ではAと～ingは能動的な関係だったが，〈A done〉は受動の関係（his arms were crossed）を表す。日本語は「腕を組んで」と「彼」を主語と想定した能動的な表現になっているが、英語では「組む」の主語はA（ここではhis arms）なので,「腕が組まれて」と受動態でなければならない。日本語に引っ張られやすい構文なので特に注意が必要。► She was sitting on a chair with her eyes closed.「彼女は目を閉じて（←英語の発想は「目が閉じられた状態で」）いすに座っていた」 " },
{ no: 60,  ja: "彼が金持ちだろうと貧乏だろうと，私は彼と結婚する。",    en: "Whether he is rich or poor, Iʼll marry him.", kaisetsu: "<whether A or B>で「AだろうとBだろうと」の意味。or はもともと「あるいは」という意味だが、ここでは〈A or B〉の形で「AだろうとBだろうと」という意味になる。<whether A or B>は、例題文のように文の初めに来ることもあれば、文の後半に置かれることもある。► Your essay should be logical whether you write it in Japanese or in English.「日本語で書こうが，英語で書こうが，小論文は論理的でなければなりません」〈whether A or B〉のBの位置にnotが置かれた〈whether A or not〉の型もよくあり，この場合は「Aだろうとなかろうと」という意味になる。or notは省略されうる。► You must do this job, whether you like it or not.「好むと好まざるとにかかわらず，君はこの仕事をしなければならない」 " },
{ no: 61,  ja: "私たちは海外の人々と意思疎通ができるよう，英語を学ぶ。",    en: "We learn English so that we can communicate with people overseas.", kaisetsu: "<so that S′can [will / may etc.] do>は「S′が～できるように/するために／～するように」という〈目的〉の意味をもつ副詞節を形成する。so that節の中のS′+ V′のV′の前には，ほとんどの場合,can[could], will[would], may[might] などの助動詞が置かれる。主節とso that ～部分の位置関係としては、常に主節が先行し、その後にso thatが来る形となる。また、主節の動詞が過去の場合、その時間に連動して、so thatの中の助動詞はcould / would / might になるので注意。これは非常に見落としやすいポイントなので要注意。► We stopped talking so that we could hear the song.「その歌が聞こえるように私たちは話すのをやめた」「S′が～しないように」と否定の〈目的〉を表す場合は，助動詞の後ろにnotを加え，〈so that S′can[will / may etc.] not do〉とする。► He jogs every day so that he will not gain weight.「体重が増えないように彼は毎日ジョギングをする」。また、so thatのthatは省略されることがある。この場合は〈so S′can[will / may etc.] do〉という形になるが，S′とV′の間にcan[could], will[would], may[might] が存在すること，そして文内容から，本来はso that節だということを見抜く。► You must work hard so you can go to a good school.「いい学校に行けるよう，懸命に励まなくてはならないよ」※ so の後ろの that が省略されている。 " },
{ no: 62,  ja: "明日雨が降ったら，あなたは何をするつもりですか？",    en: "Suppose it rains tomorrow, what will you do?", kaisetsu: "〈suppose[supposing] (that) ～〉はifと同様に副詞節を形成し，「もし～なら」という意味となる。thatは省略されることが多く，またsupposingよりも圧倒的に高い頻度でsupposeが用いられる。〈suppose[supposing] (that) ～〉も，ifと同様に仮定法，直説法の2つのケースがある。► Suppose that I were drowning, would you jump in the water to rescue me?「もし私がおぼれていたら，あなたは私を助けるために水に飛び込みますか？」※仮定法。書き手はこのような状況をまずありえないと判断している。► Supposing Tom passes this test, he can go abroad for higher education.「このテストにパスしたら，トムはより高い教育を求めて海外に行けます」※passが現在形なので直説法。書き手はトムがテストにパスすることはありうると考えている。" },
{ no: 63,  ja: "気をつけて運転するのなら，君に私の車を貸してあげよう。",    en: "Iʼll lend you my car provided that you drive carefully." },
{ no: 64,  ja: "今はもうあなたがここにいないので，私は孤独を感じている。",    en: "Now that you are not here, I feel lonely." },
{ no: 65,  ja: "たとえ昇給があったとしても，私は仕事をやめるつもりだ。",    en: "Even if I get a pay raise, I’m going to quit my job." },
{ no: 66,  ja: "天気は悪かったが，私たちはとても良い休日を過ごした。",    en: "Even though the weather was bad, we had a great holiday." },
{ no: 67,  ja: "静かにしているのなら，子どもたちはここにいてよろしい。",    en: "The children can stay here, as long as they keep quiet." },
{ no: 68,  ja: "私の知る限りでは，父はハワイには行ったことがない。",    en: "As far as I know, my father has never been to Hawaii." },
{ no: 69,  ja: "その知らせを聞くとすぐに，私は病院に急行した。",    en: "As soon as I heard the news, I rushed to the hospital." },
{ no: 70,  ja: "18歳になるまでに，信用できる人になっていなければならないよ。",    en: "By the time you are eighteen, you should be a responsible person." },
{ no: 71,  ja: "道に迷うといけないから，この地図を持っていきなさい。",    en: "Take this map in case you get lost." },
{ no: 72,  ja: "私たちはその台風が町を直撃するのではないかと心配しています。",    en: "We are afraid that the typhoon will hit our town." },
{ no: 73,  ja: "私はとても忙しいので，あなたを助けられない。",    en: "Iʼm so busy that I canʼt help you." },
{ no: 74,  ja: "彼はとても有名な人なので，私の友達は皆彼を知っている。",    en: "He is such a famous person that all my friends know him." },
{ no: 75,  ja: "いつあなたが私たちを訪ねようとも，私たちはあなたを温かく迎えます。",    en: "No matter when you visit us, we will welcome you warmly." },
{ no: 76,  ja: "今ではどこにいても簡単に連絡を取り合える。",    en: "No matter where we are, it is easy to contact each other now." },
{ no: 77,  ja: "どんなに忙しくても，父は毎朝散歩をする。",    en: "No matter how busy he is, my father takes a walk every morning." },
{ no: 78,  ja: "誰が反対しようとも，私は自分の考えを変えるつもりはない。",    en: "No matter who objects, I won’t change my mind." },
{ no: 79,  ja: "何が起ころうと，私はあなたをいつでも愛しています。",    en: "No matter what happens, Iʼll always love you." },
{ no: 80,  ja: "どちらを選ぼうと，あなたは満足するでしょう。",    en: "No matter which you choose, you will be satisfied." },
{ no: 81,  ja: "私は彼がどこに住んでいるのかを知らない。",    en: "I donʼt know where he lives." },
{ no: 82,  ja: "私は自分が歌手として成功できるなんてありえないと思った。",    en: "I thought it impossible that I could ever succeed as a singer." },
{ no: 83,  ja: "携帯電話のスイッチが切られていることをご確認ください。",    en: "Please make sure that your mobile phone is switched off." },
{ no: 84,  ja: "ケイトは自分が当然そのパーティーに招待されるものと思っていた。",    en: "Kate took it for granted that she would be invited to the party." },
{ no: 85,  ja: "宇宙空間は完全に無音だ。これはそこに空気がないからだ。",    en: "Space is completely silent. This is because there is no air there." },
{ no: 86,  ja: "実は私の会社は倒産寸前なんです。",    en: "The fact is that my company is almost bankrupt." },
{ no: 87,  ja: "ここが私が以前にカエルを捕まえた公園だ。",    en: "This is the park where I once caught a frog." },
{ no: 88,  ja: "ここが彼が住んでいる場所だ。",    en: "This is where he lives." },
{ no: 89,  ja: "彼が彼女に言ったことは本当だった。",    en: "What he said to her was true." },
{ no: 90,  ja: "彼は良い科学者であり，さらに良いことには，私たちの教師だ。",    en: "He is a good scientist, and what is better, he is our teacher." },
{ no: 91,  ja: "トムはパーティーに来られなかった。それは残念なことだった。",    en: "Tom couldnʼt come to the party, which was a pity." },
{ no: 92,  ja: "私には彼の外見からわかっていたが，彼は画家だった。",    en: "He was a painter, as I knew from his appearance." },
{ no: 93,  ja: "彼はできるだけゆっくり歩いた。",    en: "He walked as slowly as possible." },
{ no: 94,  ja: "この映画は興味深いというよりもむしろ，わくわくするものだ。",    en: "This movie is not so much interesting as exciting." },
{ no: 95,  ja: "彼に助言しようとするのは，壁に話しかけるようなものだ。",    en: "You might as well talk to the wall as try to give him advice." },
{ no: 96,  ja: "トムが日本語を話せないのと同様に，私は英語が話せない。",    en: "I can no more speak English than Tom can speak Japanese.", kaisetsu: "no more ～ than --- 「---と同様に～でない」　比較級は元々「～より---」と差の存在を示すが、比較級の前にnoがつくと,その差が「ない（つまりゼロ）」という意味になる。〈no more〉の more はmuchまたは manyの比較級だが、no moreとなると、「増加分（=more）が無い（ゼロだ）」という意味になる。つまりこの基本例文においては，私が英語を話せる度合いは，トムが日本語を話せる度合いと比べてプラスゼロ（＝イコール）であり，この文の意味は「私が英語を話せる度合いは，トムが日本語を話せる度合いと同じだ」ということになる。ただし，本構文が同等比較を表す〈as ～ as ...〉などと異なる点は，この文が「トムは日本語が話せないのだが，私も同様に英語が話せない」という否定の意味を表す点である。than以下に「そうでない」ことが自明の例が置かれることで，こうした否定のニュアンスが出ると考えられる。【改行】〈A is no more ～ than B (is ...)〉は否定のニュアンスをもち，「AはBと同様に～でない」の意味となる。この構文の主眼は，than以下に「そうでない例，ありえないことの例」を引き合いに出しながら，Aが「そうでない」ということを伝えるところにある。よって，それが伝わるのであれば，以下のような訳もありうる。「Bがそうでないのと同じように，Aもそうでない」 ※基本例文はこの訳。「Aがそうでないのは，Bがそうでないのと同じだ」► He is no more a genius than I am.「彼が天才でないのは，私がそうでないのと同じことだ。」※〈no more ～ than …〉の「～」には，（代）名詞，動詞，形容詞などさまざまな品詞が入る。また,この表現は「クジラの公式」とも呼ばれる。► A whale is no more a fish than a horse is ( a fish ).「クジラが魚でないのは馬が魚でないのと同じだ」「馬が魚でないのと同じで、クジラは魚ではない」  " },
{ no: 97,  ja: "その式典では，妻と同じように私も緊張していた。",    en: "I was no less nervous than my wife was at the ceremony.", kaisetsu: "〈no less ～ than ...〉は，No.96の〈no more ～ than ...〉と反対の意味をもつ表現で，「…と同様に～である」の意味。〈A is no less ～ than B (is ...)〉は，than以下に「そうである例」「当然であることの例」を引き合いに出しながら，Aが「そうである」ということを述べる。上記以外にも，以下のような訳がありうる。「Bがそうであるのと同じように，Aもそうである」「Aがそうであるのは，Bがそうであるのと同じだ」► She is no less beautiful than her mother.「彼女はお母さんに負けず劣らず美人だ」 " },
{ no: 98,  ja: "その部屋にはジョン以外に誰もいなかった。",    en: "There was nobody in the room other than John.", kaisetsu: "〈other than ...〉は「…以外」の意味を表す表現。「…」の部分には名詞が置かれることが多いが，動詞を中心とする句や，S′ V′を含む節，文が置かれることもある。► Little is known about the poet, other than that he died in his 20s.「20代で死んだということ以外，その詩人についてほとんど知られていない」※other thanの後ろにはthat節が置かれている。"
 },
{ no: 99,  ja: "私はコーヒーよりもむしろ紅茶が好きだ。",    en: "I prefer tea rather than coffee.", kaisetsu: "〈A rather than B〉はNo.94で扱った〈not so much A as B〉と同じ意味をもち，「BというよりもむしろA」の意味。ただし，２つの表現ではAとBの順序が逆になることに注意。<A rather than B = not so much A as B> 「BというよりむしろA」► He painted those pictures to express himself rather than to make money.＝He painted those pictures not so much to make money as to express himself.「彼はお金を稼ぐためというよりもむしろ，自分自身を表現するためにそれらの絵を描いた」なお，本構文は，〈rather A than B〉と,Aの位置がthanの後になる場合もある。► I think it’s rather green than blue.「それは青というより，むしろ緑だと思う」 " },
{ no: 100,  ja: "今晩は出かけるよりも家にいたい。",    en: "I would rather stay at home than go out tonight.", kaisetsu: "〈would rather A than B〉は，No.99で示した〈rather A than B〉のratherの前にwouldが加わった表現で，「BするよりもむしろAしたい」という〈願望〉を表す。wouldが助動詞なので、A, Bともに動詞の原形または動詞の原形から始まるまとまりが置かれるのがふつう。► I would rather be alone than be with him.「彼といるくらいならむしろ一人でいたい」" },
{ no: 101,  ja: "高く登れば登るほど，空気はますます薄くなった。",    en: "The higher I climbed, the thinner the air became." },
{ no: 102,  ja: "父親になったので，彼は今，そのぶんいっそう懸命に働く。",    en: "He works all the harder now because he has become a father." },
{ no: 103,  ja: "状況はどんどん悪くなった。",    en: "The situation got worse and worse." },
{ no: 104,  ja: "私はコーヒーよりも紅茶が好きだ。",    en: "I prefer tea to coffee." },
{ no: 105,  ja: "私はいつも忙しいわけではない。",    en: "Iʼm not always busy." },
{ no: 106,  ja: "彼の名前を知らない人は誰もいなかった。",    en: "There was nobody who didnʼt know his name." },
{ no: 107,  ja: "彼はアメリカ人ではなくカナダ人だ。",    en: "He is not American but Canadian." },
{ no: 108,  ja: "私は数学だけでなく物理も教えられます。",    en: "I can teach not only mathematics but also physics." },
{ no: 109,  ja: "祖父はめったに外出しない。",    en: "My grandfather hardly ever goes out." },
{ no: 110,  ja: "最近私は，衣服にはほとんどお金を使わない。",    en: "I spend hardly any money on clothes these days." },
{ no: 111,  ja: "彼女が家を出るとすぐに，雨が強く降り始めた。",    en: "No sooner had she left home than it started to rain heavily." },
{ no: 112,  ja: "ドアを開けるとすぐに，私は妙なにおいに気づいた。",    en: "Hardly had I opened the door when I noticed a strange smell." },
{ no: 113,  ja: "彼はただの噓つきだ。",    en: "He is nothing but a liar." },
{ no: 114,  ja: "彼はもはや子どもではない。",    en: "He is no longer a child." },
{ no: 115,  ja: "もし宝くじが当たったら，大きな家を買うのだが。",    en: "If I won a lottery, I would buy a big house." },
{ no: 116,  ja: "もしあなたが彼を助けていたら，彼は成功していただろうに。",    en: "If you had helped him, he would have succeeded." },
{ no: 117,  ja: "仮に核戦争が勃発したら，どんなことが起こるだろうか？",    en: "What would happen if a nuclear war were to break out?" },
{ no: 118,  ja: "彼はまるでプロの歌手であるかのように歌う。",    en: "He sings as if he were a professional singer." },
{ no: 119,  ja: "水がなければ，どんな生物も生きられないだろう。",    en: "If it were not for water, no creature could live." },
{ no: 120,  ja: "あなたの助言がなかったら，私はそのコンテストで優勝していなかっただろう。",    en: "If it had not been for your advice, I would not have won the contest." },
{ no: 121,  ja: "車を持っていればなぁ。",    en: "I wish I had a car." },
{ no: 122,  ja: "もう寝る時間だよ。",    en: "Itʼs time you went to bed." },
{ no: 123,  ja: "ボールでうちの窓を割ったのはお宅の息子さんです。",    en: "It was your son that broke our window with a ball." },
{ no: 124,  ja: "私が彼に会ったのは昨日のことだ。",    en: "It was yesterday that I met him." },
{ no: 125,  ja: "彼はお金持ちだが幸せではない。",    en: "Rich as he is, he is not happy." },
{ no: 126,  ja: "箱の中には３匹のネコがいる。",    en: "In the box are three cats." },
{ no: 127,  ja: "彼女が一等賞を取るなんて夢にも思わなかった。",    en: "Little did I dream that she would win first prize." },
{ no: 128,  ja: "君が会議に出ないのなら，僕も出ないつもりだ。",    en: "If you donʼt attend the meeting, neither will I." },
{ no: 129,  ja: "僕は車の運転ができるが，妻もできる。",    en: "I can drive a car, and so can my wife." },
{ no: 130,  ja: "彼が優れたリーダーだということは明らかだ。",    en: "Obvious is the fact that he is an excellent leader." },
{ no: 131,  ja: "この事業は，私は成功すると思う。",    en: "This project, I think, will be successful." },
{ no: 132,  ja: "父は，私が若かったとき，銀行に勤めていた。",    en: "My father, when I was young, worked for a bank." },
{ no: 133,  ja: "若かった頃，彼女はとても上品だった。",    en: "When young, she was very elegant." },
{ no: 134,  ja: "自分が鳥なら，あなたのところに飛んでいけるのに。",    en: "Were I a bird, I could fly to you." },
{ no: 135,  ja: "その博物館が来月閉館になるというニュースを聞きましたか？",    en: "Did you hear the news that the museum is closing next month?" },
{ no: 136,  ja: "彼は日本を去る決心をした。",    en: "He made a decision to leave Japan." },
{ no: 137,  ja: "彼は命を失う危険にあった。",    en: "He was at risk of losing his life." },
{ no: 138,  ja: "君はお金持ちだが，僕は貧乏だ。",    en: "You are rich, while I am poor." },
{ no: 139,  ja: "私には２人の姉がいる。１人は医者で，もう１人は看護師だ。",    en: "I have two sisters. One is a doctor and the other is a nurse." },
{ no: 140,  ja: "ネコが好きな人もいれば，イヌが好きな人もいる。",    en: "Some like cats, and others like dogs." },
{ no: 141,  ja: "私は大学ではフランス語かドイツ語のどちらかを学びたい。",    en: "I want to study either French or German at university." },
{ no: 142,  ja: "私は歌うことも踊ることもできない。",    en: "I can neither sing nor dance." },
{ no: 143,  ja: "この本は面白くもあり役にもたつ。",    en: "This book is both interesting and useful." },
{ no: 144,  ja: "4年前，私はこれと同じ腕時計を購入した。",    en: "Four years ago, I purchased the same watch as this." },
{ no: 145,  ja: "ロンドンのような大都市に住むことには多くの利点がある。",    en: "There are a lot of advantages to living in such a big city as London." },
{ no: 146,  ja: "スマートフォンの発明は我々の社会にとって良いことだったのか？",    en: "Was the invention of the smartphone a good thing for our society?" },
{ no: 147,  ja: "彼が仕事を辞めることを決心したのでみんなが驚いた。",    en: "His decision to quit his job surprised everyone." },
{ no: 148,  ja: "私はこれに似た帽子を持っている。",    en: "I have a hat similar to this." },
{ no: 149,  ja: "私は，ただ安かったという理由だけでこのコンピューターを買いました。",    en: "I bought this computer only because it was cheap." },
{ no: 150,  ja: "ロボットが芸術作品を生み出すときが来るかもしれない。",    en: "The time may come when robots create works of art." },
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = QUIZ_DATA;
}
