const QUIZ_DATA = [
 { id: "001", en: "It is certain that climate change is very serious.", jp: "気候変動が非常に深刻であることは確かだ。" },
  { id: "002", en: "It is difficult to change oneʼs behavior.", jp: "人の行動を変えるのは難しい。" },
  { id: "003", en: "It took her three hours to write the letter.", jp: "彼女がその手紙を書くのに３時間かかった。" },
  { id: "004", en: "It cost him 2,500 dollars to ski in Canada.", jp: "彼がカナダでスキーをするのに2,500ドルかかった。" },
  { id: "005", en: "From this evidence, it follows that she is innocent.", jp: "この証拠から，彼女は無実だということになる。" },
  { id: "006", en: "It is five kilometers from here to Yokohama Station.", jp: "ここから横浜駅までは５キロの距離だ。" },
  { id: "007", en: "It has been three months since I last saw you.", jp: "あなたに最後にお会いして以来，３か月が経つ。" },
  { id: "008", en: "It will be several years before he can buy his own house.", jp: "彼が自分の家を買えるまで数年かかるだろう。" },
  { id: "009", en: "Lucas seems to love Emma.", jp: "ルーカスはエマのことが大好きなようだ。" },
  { id: "010", en: "My son will learn to read and write soon.", jp: "息子はじきに読み書きができるようになるだろう。" },
  { id: "011", en: "He tends to speak in a loud voice.", jp: "彼は大声で話す傾向がある。" },
  { id: "012", en: "I managed to finish my report by the deadline.", jp: "私はどうにか締め切りまでにレポートを仕上げることができた。" },
  { id: "013", en: "I used to swim in the river near my house.", jp: "昔はよく家の近くの川で泳いだものだ。" },
  { id: "014", en: "The train is about to leave.", jp: "今まさに電車が出るところだ。" },
  { id: "015", en: "The man is said to possess great wealth.", jp: "その男は莫大な富を持っていると言われている。" },
  { id: "016", en: "Lisa may well leave her job soon.", jp: "リサはたぶん，じきに仕事を辞めるだろう。" },
  { id: "017", en: "The baby kept crying all night.", jp: "その赤ちゃんは一晩中泣き続けた。" },
  { id: "018", en: "Heʼs late.  He may have missed the train.", jp: "彼は遅いな。電車に乗り遅れたのかもしれない。" },
  { id: "019", en: "They were too tired to move.", jp: "彼らはあまりにも疲れていて動けなかった。" },
  { id: "020", en: "Her skirt was long enough to touch the floor.", jp: "彼女のスカートは床に触れるほど長かった。" },
  { id: "021", en: "We are working hard in order to create a better society.", jp: "より良い社会を創るために私たちは懸命に働いている。" },
  { id: "022", en: "We cannot afford to buy a house.", jp: "私たちは家を買う余裕がない。" },
  { id: "023", en: "She asked me to open the window.", jp: "彼女は私に窓を開けるよう頼んだ。" },
  { id: "024", en: "Our coach sometimes makes us practice even on Sundays.", jp: "コーチは時々日曜日にも私たちに練習させる。" },
  { id: "025", en: "Dr.Brown had the nurse take my blood pressure.", jp: "ブラウン医師は看護師に私の血圧を測らせた。" },
  { id: "026", en: "I let my son play my guitar.", jp: "私は息子に自分のギターを弾かせてやった。" },
  { id: "027", en: "We helped the man push his car in the deep snow.", jp: "私たちは深い雪の中，その男性が車を押すのを手助けした。" },
  { id: "028", en: "His wife saw him go into the shop.", jp: "彼の妻は彼がその店に入るのを見た。" },
  { id: "029", en: "I tried it again, only to fail.", jp: "私はもう一度挑戦したが，結局失敗しただけだった。" },
  { id: "030", en: "She went out, never to return.", jp: "彼女は外出して，二度と戻ってこなかった。" },
  { id: "031", en: "The president is to arrive here soon.", jp: "大統領は間もなくここに着くことになっている。" },
  { id: "032", en: "We talked about what to do next.", jp: "私たちは次に何をするべきかについて話した。" },
  { id: "033", en: "I had no choice but to sell my car.", jp: "私には車を売るほかなかった。" },
  { id: "034", en: "Do you have something to do with the organization?", jp: "あなたはその組織と何らかの関係がありますか？" },
  { id: "035", en: "He improved his English by reading books and newspapers.", jp: "彼は本と新聞を読むことで自分の英語に磨きをかけた。" },
  { id: "036", en: "He left the room without saying anything.", jp: "彼は何も言わないで部屋を出ていった。" },
  { id: "037", en: "In reforming education, studentsʼ opinions should be considered.", jp: "教育を改革する際には，学生の意見を考慮に入れるべきだ。" },
  { id: "038", en: "On hearing the sound, the dog ran away.", jp: "その音を聞くや否や，そのイヌは逃げていった。" },
  { id: "039", en: "The children are working instead of going to school.", jp: "その子どもたちは学校に行くかわりに働いている。" },
  { id: "040", en: "We are looking forward to seeing you.", jp: "私たちはあなたにお会いするのを楽しみにしています。" },
  { id: "041", en: "This city is worth visiting.", jp: "この都市は訪れる価値がある。" },
  { id: "042", en: "I am interested in joining new clubs when I go to university.", jp: "私は大学に行ったら新しいクラブに入ることに興味をもっている。" },
  { id: "043", en: "The windy weather prevented many trains from running on time.", jp: "（強風が，多くの電車が時間通りに運行することを妨げた。→）\n強風のために，多くの電車が時間通りに運行できなかった。" },
  { id: "044", en: "I cannot help playing games every night.", jp: "私は毎晩ゲームをせずにはいられない。" },
  { id: "045", en: "There is no knowing what he will do next.", jp: "彼が次に何をするか，知ることはできない。" },
  { id: "046", en: "Itʼs no use threatening me.", jp: "私を脅しても無駄ですよ。" },
  { id: "047", en: "We saw a cat chasing a little mouse.", jp: "私たちはネコが小さなネズミを追いかけているのを見た。" },
  { id: "048", en: "I heard my name called from behind.", jp: "私は自分の名前が後ろから呼ばれるのを聞いた。" },
  { id: "049", en: "We kept the stove burning throughout the night.", jp: "私たちは一晩中ストーブをたいておいた。" },
  { id: "050", en: "Please keep your nose and mouth covered with a mask.", jp: "鼻と口がマスクで覆われたままにしておいてください。" },
  { id: "051", en: "I had my PC checked by a specialist.", jp: "私は専門家に自分のパソコンをチェックしてもらった。" },
  { id: "052", en: "I couldnʼt make myself understood in English.", jp: "私は英語で理解してもらえなかった。" },
  { id: "053", en: "Not feeling well, I went to bed early.", jp: "気分が良くなかったので，私は早くベッドに入った。" },
  { id: "054", en: "Written in easy English, this book is suitable for beginners.", jp: "簡単な英語で書かれているので，この本は初心者に向いている。" },
  { id: "055", en: "The rain beginning to fall, they decided to take a taxi.", jp: "雨が降りはじめたので，彼らはタクシーに乗ることにした。" },
  { id: "056", en: "Strictly speaking, his opinion is a little different from mine.", jp: "厳密に言えば，彼の意見は僕の意見とは少し異なる。" },
  { id: "057", en: "We spent two weeks researching the topic.", jp: "そのテーマを調査するのに私たちは２週間を費やした。" },
  { id: "058", en: "Donʼt leave your car with the engine running.", jp: "エンジンをかけたまま，車を離れないでください。" },
  { id: "059", en: "He was standing with his arms crossed.", jp: "彼は（腕が組まれた状態で→）腕を組んで立っていた。" },
  { id: "060", en: "Whether he is rich or poor, Iʼll marry him.", jp: "彼が金持ちだろうと貧乏だろうと，私は彼と結婚する。" },
  { id: "061", en: "We learn English so that we can communicate with people overseas.", jp: "私たちは海外の人々と意思疎通ができるよう，英語を学ぶ。" },
  { id: "062", en: "Suppose it rains tomorrow, what will you do?", jp: "明日雨が降ったら，あなたは何をするつもりですか？" },
  { id: "063", en: "Iʼll lend you my car provided that you drive carefully.", jp: "気をつけて運転するのなら，君に私の車を貸してあげよう。" },
  { id: "064", en: "Now that you are not here, I feel lonely.", jp: "今はもうあなたがここにいないので，私は孤独を感じている。" },
  { id: "065", en: "Even if I get a pay raise, I’m going to quit my job.", jp: "たとえ昇給があったとしても，私は仕事をやめるつもりだ。" },
  { id: "066", en: "Even though the weather was bad, we had a great holiday.", jp: "天気は悪かったが，私たちはとても良い休日を過ごした。" },
  { id: "067", en: "The children can stay here, as long as they keep quiet.", jp: "静かにしているのなら，子どもたちはここにいてよろしい。" },
  { id: "068", en: "As far as I know, my father has never been to Hawaii.", jp: "私の知る限りでは，父はハワイには行ったことがない。" },
  { id: "069", en: "As soon as I heard the news, I rushed to the hospital.", jp: "その知らせを聞くとすぐに，私は病院に急行した。" },
  { id: "070", en: "By the time you are eighteen, you should be a responsible person.", jp: "18歳になるまでに，信用できる人になっていなければならないよ。" },
  { id: "071", en: "Take this map in case you get lost.", jp: "道に迷うといけないから，この地図を持っていきなさい。" },
  { id: "072", en: "We are afraid that the typhoon will hit our town.", jp: "私たちはその台風が町を直撃するのではないかと心配しています。" },
  { id: "073", en: "Iʼm so busy that I canʼt help you.", jp: "私はとても忙しいので，あなたを助けられない。" },
  { id: "074", en: "He is such a famous person that all my friends know him.", jp: "彼はとても有名な人なので，私の友達は皆彼を知っている。" },
  { id: "075", en: "No matter when you visit us, we will welcome you warmly.", jp: "いつあなたが私たちを訪ねようとも，私たちはあなたを温かく迎えます。" },
  { id: "076", en: "No matter where we are, it is easy to contact each other now.", jp: "今ではどこにいても簡単に連絡を取り合える。" },
  { id: "077", en: "No matter how busy he is, my father takes a walk every morning.", jp: "どんなに忙しくても，父は毎朝散歩をする。" },
  { id: "078", en: "No matter who objects, I won’t change my mind.", jp: "誰が反対しようとも，私は自分の考えを変えるつもりはない。" },
  { id: "079", en: "No matter what happens, Iʼll always love you.", jp: "何が起ころうと，私はあなたをいつでも愛しています。" },
  { id: "080", en: "No matter which you choose, you will be satisfied.", jp: "どちらを選ぼうと，あなたは満足するでしょう。" },
  { id: "081", en: "I donʼt know where he lives.", jp: "私は彼がどこに住んでいるのかを知らない。" },
  { id: "082", en: "I thought it impossible that I could ever succeed as a singer.", jp: "私は自分が歌手として成功できるなんてありえないと思った。" },
  { id: "083", en: "Please make sure that your mobile phone is switched off.", jp: "携帯電話のスイッチが切られていることをご確認ください。" },
  { id: "084", en: "Kate took it for granted that she would be invited to the party.", jp: "ケイトは自分が当然そのパーティーに招待されるものと思っていた。" },
  { id: "085", en: "Space is completely silent.  This is because there is no air there.", jp: "宇宙空間は完全に無音だ。これはそこに空気がないからだ。" },
  { id: "086", en: "The fact is that my company is almost bankrupt.", jp: "実は私の会社は倒産寸前なんです。" },
  { id: "087", en: "This is the park where I once caught a frog.", jp: "ここが私が以前にカエルを捕まえた公園だ。" },
  { id: "088", en: "This is where he lives.", jp: "ここが彼が住んでいる場所だ。" },
  { id: "089", en: "What he said to her was true.", jp: "彼が彼女に言ったことは本当だった。" },
  { id: "090", en: "He is a good scientist, and what is better, he is our teacher.", jp: "彼は良い科学者であり，さらに良いことには，私たちの教師だ。" },
  { id: "091", en: "Tom couldnʼt come to the party, which was a pity.", jp: "トムはパーティーに来られなかった。それは残念なことだった。" },
  { id: "092", en: "He was a painter, as I knew from his appearance.", jp: "私には彼の外見からわかっていたが，彼は画家だった。" },
  { id: "093", en: "He walked as slowly as possible.", jp: "彼はできるだけゆっくり歩いた。" },
  { id: "094", en: "This movie is not so much interesting as exciting.", jp: "この映画は興味深いというよりもむしろ，わくわくするものだ。" },
  { id: "095", en: "You might as well talk to the wall as try to give him advice.", jp: "彼に助言しようとするのは，壁に話しかけるようなものだ。" },
  { id: "096", en: "I can no more speak English than Tom can speak Japanese.", jp: "トムが日本語を話せないのと同様に，私は英語が話せない。" },
  { id: "097", en: "I was no less nervous than my wife was at the ceremony.", jp: "その式典では，妻と同じように私も緊張していた。" },
  { id: "098", en: "There was nobody in the room other than John.", jp: "その部屋にはジョン以外に誰もいなかった。" },
  { id: "099", en: "I prefer tea rather than coffee.", jp: "私はコーヒーよりもむしろ紅茶が好きだ。" },
  { id: "100", en: "I would rather stay at home than go out tonight.", jp: "今晩は出かけるよりも家にいたい。" },
  { id: "101", en: "The higher I climbed, the thinner the air became.", jp: "高く登れば登るほど，空気はますます薄くなった。" },
  { id: "102", en: "He works all the harder now because he has become a father.", jp: "父親になったので，彼は今，そのぶんいっそう懸命に働く。" },
  { id: "103", en: "The situation got worse and worse.", jp: "状況はどんどん悪くなった。" },
  { id: "104", en: "I prefer tea to coffee.", jp: "私はコーヒーよりも紅茶が好きだ。" },
  { id: "105", en: "Iʼm not always busy.", jp: "私はいつも忙しいわけではない。" },
  { id: "106", en: "There was nobody who didnʼt know his name.", jp: "彼の名前を知らない人は誰もいなかった。" },
  { id: "107", en: "He is not American but Canadian.", jp: "彼はアメリカ人ではなくカナダ人だ。" },
  { id: "108", en: "I can teach not only mathematics but also physics.", jp: "私は数学だけでなく物理も教えられます。" },
  { id: "109", en: "My grandfather hardly ever goes out.", jp: "祖父はめったに外出しない。" },
  { id: "110", en: "I spend hardly any money on clothes these days.", jp: "最近私は，衣服にはほとんどお金を使わない。" },
  { id: "111", en: "No sooner had she left home than it started to rain heavily.", jp: "彼女が家を出るとすぐに，雨が強く降り始めた。" },
  { id: "112", en: "Hardly had I opened the door when I noticed a strange smell.", jp: "ドアを開けるとすぐに，私は妙なにおいに気づいた。" },
  { id: "113", en: "He is nothing but a liar.", jp: "彼はただの噓つきだ。" },
  { id: "114", en: "He is no longer a child.", jp: "彼はもはや子どもではない。" },
  { id: "115", en: "If I won a lottery, I would buy a big house.", jp: "もし宝くじが当たったら，大きな家を買うのだが。" },
  { id: "116", en: "If you had helped him, he would have succeeded.", jp: "もしあなたが彼を助けていたら，彼は成功していただろうに。" },
  { id: "117", en: "What would happen if a nuclear war were to break out?", jp: "仮に核戦争が勃発したら，どんなことが起こるだろうか？" },
  { id: "118", en: "He sings as if he were a professional singer.", jp: "彼はまるでプロの歌手であるかのように歌う。" },
  { id: "119", en: "If it were not for water, no creature could live.", jp: "水がなければ，どんな生物も生きられないだろう。" },
  { id: "120", en: "If it had not been for your advice, I would not have won the contest.", jp: "あなたの助言がなかったら，私はそのコンテストで優勝していなかっただろう。" },
  { id: "121", en: "I wish I had a car.", jp: "車を持っていればなぁ。" },
  { id: "122", en: "Itʼs time you went to bed.", jp: "もう寝る時間だよ。" },
  { id: "123", en: "It was your son that broke our window with a ball.", jp: "ボールでうちの窓を割ったのはお宅の息子さんです。" },
  { id: "124", en: "It was yesterday that I met him.", jp: "私が彼に会ったのは昨日のことだ。" },
  { id: "125", en: "Rich as he is, he is not happy.", jp: "彼はお金持ちだが幸せではない。" },
  { id: "126", en: "In the box are three cats.", jp: "箱の中には３匹のネコがいる。" },
  { id: "127", en: "Little did I dream that she would win first prize.", jp: "彼女が一等賞を取るなんて夢にも思わなかった。" },
  { id: "128", en: "If you donʼt attend the meeting, neither will I.", jp: "君が会議に出ないのなら，僕も出ないつもりだ。" },
  { id: "129", en: "I can drive a car, and so can my wife.", jp: "僕は車の運転ができるが，妻もできる。" },
  { id: "130", en: "Obvious is the fact that he is an excellent leader.", jp: "彼が優れたリーダーだということは明らかだ。" },
  { id: "131", en: "This project, I think, will be successful.", jp: "この事業は，私は成功すると思う。" },
  { id: "132", en: "My father, when I was young, worked for a bank.", jp: "父は，私が若かったとき，銀行に勤めていた。" },
  { id: "133", en: "When young, she was very elegant.", jp: "若かった頃，彼女はとても上品だった。" },
  { id: "134", en: "Were I a bird, I could fly to you.", jp: "自分が鳥なら，あなたのところに飛んでいけるのに。" },
  { id: "135", en: "Did you hear the news that the museum is closing next month?", jp: "その博物館が来月閉館になるというニュースを聞きましたか？" },
  { id: "136", en: "He made a decision to leave Japan.", jp: "彼は日本を去る決心をした。" },
  { id: "137", en: "He was at risk of losing his life.", jp: "彼は命を失う危険にあった。" },
  { id: "138", en: "You are rich, while I am poor.", jp: "君はお金持ちだが，僕は貧乏だ。" },
  { id: "139", en: "I have two sisters.  One is a doctor and the other is a nurse.", jp: "私には２人の姉がいる。１人は医者で，もう１人は看護師だ。" },
  { id: "140", en: "Some like cats, and others like dogs.", jp: "ネコが好きな人もいれば，イヌが好きな人もいる。" },
  { id: "141", en: "I want to study either French or German at university.", jp: "私は大学ではフランス語かドイツ語のどちらかを学びたい。" },
  { id: "142", en: "I can neither sing nor dance.", jp: "私は歌うことも踊ることもできない。" },
  { id: "143", en: "This book is both interesting and useful.", jp: "この本は面白くもあり役にもたつ。" },
  { id: "144", en: "Four years ago, I purchased the same watch as this.", jp: "4年前，私はこれと同じ腕時計を購入した。" },
  { id: "145", en: "There are a lot of advantages to living in such a big city as London.", jp: "ロンドンのような大都市に住むことには多くの利点がある。" },
  { id: "146", en: "Was the invention of the smartphone a good thing for our society?", jp: "スマートフォンの発明は我々の社会にとって良いことだったのか？" },
  { id: "147", en: "His decision to quit his job surprised everyone.", jp: "彼が仕事を辞めることを決心したのでみんなが驚いた。" },
  { id: "148", en: "I have a hat similar to this.", jp: "私はこれに似た帽子を持っている。" },
  { id: "149", en: "I bought this computer only because it was cheap.", jp: "私は，ただ安かったという理由だけでこのコンピューターを買いました。" },
  { id: "150", en: "The time may come when robots create works of art.", jp: "ロボットが芸術作品を生み出すときが来るかもしれない。" },
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = QUIZ_DATA;
}
